points:
  blocks:

    # ===== OVERWORLD =====

    COAL_ORE: 1
    DEEPSLATE_COAL_ORE: 1

    COPPER_ORE: 2
    DEEPSLATE_COPPER_ORE: 2

    IRON_ORE: 3
    DEEPSLATE_IRON_ORE: 3

    GOLD_ORE: 5
    DEEPSLATE_GOLD_ORE: 5

    REDSTONE_ORE: 4
    DEEPSLATE_REDSTONE_ORE: 4

    LAPIS_ORE: 4
    DEEPSLATE_LAPIS_ORE: 4

    DIAMOND_ORE: 10
    DEEPSLATE_DIAMOND_ORE: 10

    EMERALD_ORE: 12
    DEEPSLATE_EMERALD_ORE: 12


    # ===== NETHER =====

    NETHER_QUARTZ_ORE: 3
    NETHER_GOLD_ORE: 6
    ANCIENT_DEBRIS: 20